repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.277
    hooks:
    - id: ruff
      args: ["--fix"]
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black